#!/usr/bin/env bash
# Deprecated: dock icon is now generated by generate-app-icon.sh (squircle mask).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
exec "$ROOT/assets/scripts/generate-app-icon.sh" "$@"
